config/routes.rb
Final::Application.routes.draw do
  root to: 'items#index'
  resources :copies
  resources :boxes
  resources :items
  devise_for :users

  

end

app/models/box.rb
class Box < ActiveRecord::Base
  has_many :copies
end

app/models/copy.rb
class Copy < ActiveRecord::Base
  belongs_to :item
  belongs_to :box
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :copies
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render action: 'show', status: :created, location: @box }
      else
        format.html { render action: 'new' }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:name, :barcode)
    end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :set_copy, only: [:show, :edit, :update, :destroy]

  # GET /copies
  # GET /copies.json
  def index
    @copies = Copy.all
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
  end

  # GET /copies/new
  def new
    @copy = Copy.new
  end

  # GET /copies/1/edit
  def edit
  end

  # POST /copies
  # POST /copies.json
  def create
    @copy = Copy.new(copy_params)

    respond_to do |format|
      if @copy.save
        format.html { redirect_to @copy, notice: 'Copy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @copy }
      else
        format.html { render action: 'new' }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copies/1
  # PATCH/PUT /copies/1.json
  def update
    respond_to do |format|
      if @copy.update(copy_params)
        format.html { redirect_to @copy, notice: 'Copy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @copy.destroy
    respond_to do |format|
      format.html { redirect_to copies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copy
      @copy = Copy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copy_params
      params.require(:copy).permit(:item_id, :box_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :item_type, :barcode, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/boxes/_form.html.haml
= form_for @box do |f|
  - if @box.errors.any?
    #error_explanation
      %h2= "#{pluralize(@box.errors.count, "error")} prohibited this box from being saved:"
      %ul
        - @box.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :barcode
    = f.text_field :barcode
  .actions
    = f.submit 'Save'

app/views/boxes/edit.html.haml
%h1 Editing box

= render 'form'

= link_to 'Show', @box
\|
= link_to 'Back', boxes_path

app/views/boxes/index.html.haml
%h1 Listing boxes

%table
  %tr
    %th Name
    %th Barcode
    %th
    %th
    %th

  - @boxes.each do |box|
    %tr
      %td= box.name
      %td= box.barcode
      %td= link_to 'Show', box
      %td= link_to 'Edit', edit_box_path(box)
      %td= link_to 'Destroy', box, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Box', new_box_path

app/views/boxes/new.html.haml
%h1 New box

= render 'form'

= link_to 'Back', boxes_path

app/views/boxes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @box.name
%p
  %b Barcode:
  = @box.barcode
%p
  %b= "Items in #{@box.name}"
  -@box.copies.each do |c|
    %li= c.item.name

= link_to 'Edit', edit_box_path(@box)
\|
= link_to 'Back', boxes_path

app/views/copies/_form.html.haml
= form_for @copy do |f|
  - if @copy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@copy.errors.count, "error")} prohibited this copy from being saved:"
      %ul
        - @copy.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :item
    //= f.text_field :item_id
    = f.collection_select(:item_id, Item.all, :id, :name)
  .field
    = f.label :box
    //= f.text_field :box_id
    = f.collection_select(:box_id, Box.all, :id, :name)
  .actions
    = f.submit 'Save'

app/views/copies/edit.html.haml
%h1 Editing copy

= render 'form'

= link_to 'Show', @copy
\|
= link_to 'Back', copies_path

app/views/copies/index.html.haml
%h1 Listing copies

%table
  %tr
    %th Item
    %th Box
    %th
    %th
    %th

  - @copies.each do |copy|
    %tr
      %td= copy.item.name
      %td= copy.box.name
      %td= link_to 'Show', copy
      %td= link_to 'Edit', edit_copy_path(copy)
      %td= link_to 'Destroy', copy, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Copy', new_copy_path

app/views/copies/new.html.haml
%h1 New copy

= render 'form'

= link_to 'Back', copies_path

app/views/copies/show.html.haml
%p#notice= notice

%p
  %b Item:
  = @copy.item.name
%p
  %b Box:
  = @copy.box.name

= link_to 'Edit', edit_copy_path(@copy)
\|
= link_to 'Back', copies_path

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :item_type
    = f.text_field :item_type
  .field
    = f.label :barcode
    = f.text_field :barcode
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %tr
    %th Name
    %th Item type
    %th Barcode
    %th Price
    %th
    %th
    %th

  - @items.each do |item|
    %tr
      %td= item.name
      %td= item.item_type
      %td= item.barcode
      %td= item.price
      %td= link_to 'Show', item
      %td= link_to 'Edit', edit_item_path(item)
      %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item', new_item_path
= link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Item type:
  = @item.item_type
%p
  %b Barcode:
  = @item.barcode
%p
  %b Price:
  = @item.price

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=params.inspect%>
<p></p>
<%= link_to 'Items', items_path %>
<%= link_to 'Boxes', boxes_path %>
<%= link_to 'Copies', copies_path %>

<%= yield %>

</body>
</html>